[project]
name = "dnd-person-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.22.0",
    "pydantic-settings>=2.12.0",
    "pydentic>=0.0.1.dev3",
    "requests>=2.32.5",
]
